project:
  type: website
  output-dir: docs

website:
  title: "Samuel Beltrán"
  google-analytics: "G-PETD747FB9"
  navbar:
    left:
      - text: "Inicio"
        file: index.qmd
      - text : "Dashboards"
        href : dashboard.qmd
      - about.qmd
      - icon: github
        href: https://github.com/Samuelb1992
format:
  html:
    theme:
    - darkly
    - theme.scss
