project:
  type: website
  output-dir: docs

website:
  title: "Samuel Beltrán"
  navbar:
    background: "#00ABB3"
    foreground: "#FFFFFF"
    left:
      - text: "Inicio"
        file: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: theme.scss



